repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
    - id: mixed-line-ending
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
